# Generated by Django 4.2.30 on 2026-07-21 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ERPModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="모듈명")),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="모듈코드"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="📦", max_length=10, verbose_name="아이콘"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
            ],
            options={
                "verbose_name": "ERP 모듈",
                "verbose_name_plural": "ERP 모듈",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ERPVariable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("company", "회사정보"),
                            ("purchase", "구매"),
                            ("sales", "영업"),
                            ("inventory", "재고"),
                            ("accounting", "회계"),
                            ("hr", "인사"),
                            ("common", "공통"),
                        ],
                        default="common",
                        max_length=20,
                        verbose_name="카테고리",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="변수키"
                    ),
                ),
                (
                    "label",
                    models.CharField(max_length=100, verbose_name="변수명(한글)"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "sample_value",
                    models.CharField(blank=True, max_length=200, verbose_name="샘플값"),
                ),
            ],
            options={
                "verbose_name": "ERP 변수",
                "verbose_name_plural": "ERP 변수",
                "ordering": ["category", "key"],
            },
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "menu_type",
                    models.CharField(
                        choices=[("input", "입력메뉴"), ("output", "출력메뉴")],
                        default="input",
                        max_length=10,
                        verbose_name="메뉴 유형",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="메뉴명")),
                ("code", models.CharField(max_length=30, verbose_name="메뉴코드")),
                (
                    "icon",
                    models.CharField(
                        default="📝", max_length=10, verbose_name="아이콘"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0, verbose_name="순서")),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="menu_items",
                        to="erp_templates.erpmodule",
                        verbose_name="ERP 모듈",
                    ),
                ),
            ],
            options={
                "verbose_name": "메뉴 항목",
                "verbose_name_plural": "메뉴 항목",
                "ordering": ["menu_type", "order"],
                "unique_together": {("module", "code")},
            },
        ),
        migrations.CreateModel(
            name="PrintForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="양식명")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "canvas_data",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="캔버스 데이터"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="썸네일",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="기본양식"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "menu_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="print_forms",
                        to="erp_templates.menuitem",
                        verbose_name="메뉴 항목",
                    ),
                ),
            ],
            options={
                "verbose_name": "인쇄양식",
                "verbose_name_plural": "인쇄양식",
                "ordering": ["-is_default", "name"],
            },
        ),
    ]
